// Here we create all our TYPES.

export const GETALLCOUNTRIES = "GETALLCOUNTRIES";
export const GETCOUNTRYBYID = "GETCOUNTRYBYID";
export const GETALLCOUNTRIESBYNAME = "GETALLCOUNTRIESBYNAME";
export const GETALLACTIVITIES = "GETALLACTIVITIES";
export const DELETEACTIVITY = "DELETEACTIVITY";
export const POSTACTIVITY = "POSTACTIVITY";
export const PUTACTIVITY = "PUTACTIVITY";
export const SET_ACCESS = "SET_ACCESS";
export const FILTER_COUNTRIES_BY_CONTINENT = "FILTER_COUNTRIES_BY_CONTINENT";
export const ORDER_COUNTRIES = "ORDER_COUNTRIES";
export const FILTER_COUNTRIES_BY_SUBREGION = "FILTER_COUNTRIES_BY_SUBREGION";
export const SEE_ALL = "SEE_ALL";
export const SET_TESTER = "SET_TESTER";
export const SET_SEE_ALL = "SET_SEE_ALL";
export const CLEAN_COUNTRY_BY_ID = "CLEAN_COUNTRY_BY_ID";
export const CLEAN_ALL = "CLEAN_ALL";
export const GET_ACTIVITY_BY_ID = "GET_ACTIVITY_BY_ID";
export const FILTER_BY_ACTIVITIES = "FILTER_BY_ACTIVITIES";
export const SET_FILTER_AND_ORDER = "SET_FILTER_AND_ORDER";
export const CLEAN_SEARCH_RESULTS = "CLEAN_SEARCH_RESULTS";
export const POSTING = "POSTING";
export const CLEAN_ALL_ACTIVITIES = "CLEAN_ALL_ACTIVITIES";
export const SET_SEARCH = "SET_SEARCH";
export const SET_ORDER_OR_FILTER = "SET_ORDER_OR_FILTER";
